/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.sql.*;
import clases.Conexion;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class Capturista extends javax.swing.JFrame {

    String user, name_user;
    int session_user;

    public Capturista() {
        initComponents();
        user = Login.user;
        session_user = Administrador.session_user;

        setSize(550, 300);
        setResizable(false);
        setTitle("Capturista - Sesión de " + user);
        setLocationRelativeTo(null);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icon);
        this.repaint();

        if (session_user == 1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }

        try {
            Connection cn = Conexion.conect();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre_usuario from usuarios where username = '" + user + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                name_user = rs.getString("nombre_usuario");
                label_userName.setText("Bienvenido " + name_user);
            }

        } catch (SQLException e) {
            System.out.println("ERROR en consultar nombre del capturista.");
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_userName = new javax.swing.JLabel();
        btn_registerCustomer = new javax.swing.JButton();
        label_registerCustomer = new javax.swing.JLabel();
        btn_manageClients = new javax.swing.JButton();
        label_manageClients = new javax.swing.JLabel();
        btn_print = new javax.swing.JButton();
        label_print = new javax.swing.JLabel();
        label_Footer = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_userName.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        label_userName.setForeground(new java.awt.Color(255, 255, 255));
        label_userName.setText("User");
        getContentPane().add(label_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn_registerCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_registerCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registerCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 100));

        label_registerCustomer.setForeground(new java.awt.Color(255, 255, 255));
        label_registerCustomer.setText("Registrar Cliente");
        getContentPane().add(label_registerCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        btn_manageClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationuser.png"))); // NOI18N
        btn_manageClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageClientsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_manageClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 120, 100));

        label_manageClients.setForeground(new java.awt.Color(255, 255, 255));
        label_manageClients.setText("Gestionar Clientes");
        getContentPane().add(label_manageClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        getContentPane().add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 120, 100));

        label_print.setForeground(new java.awt.Color(255, 255, 255));
        label_print.setText("Imprimir clientes");
        getContentPane().add(label_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        label_Footer.setText("Creado por MrlnTrrzs13");
        getContentPane().add(label_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerCustomerActionPerformed
        RegistrarClientes registerClients = new RegistrarClientes();
        registerClients.setVisible(true);
    }//GEN-LAST:event_btn_registerCustomerActionPerformed

    private void btn_manageClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageClientsActionPerformed
        GestionarClientes manageClients = new GestionarClientes();
        manageClients.setVisible(true);
    }//GEN-LAST:event_btn_manageClientsActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        Document document = new Document();

        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(document, new FileOutputStream(ruta + "/Documents/ListaClientes.pdf"));

            com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src/images/BannerPDF.jpg");
            header.scaleToFit(650, 1000);
            header.setAlignment(Chunk.ALIGN_CENTER);

            Paragraph paragraph = new Paragraph();
            paragraph.setAlignment(Paragraph.ALIGN_CENTER);
            paragraph.add("Lista de clientes.");
            paragraph.setFont(FontFactory.getFont("Tahoma", 18, Font.BOLD, BaseColor.DARK_GRAY));

            document.open();
            document.add(header);
            document.add(paragraph);

            PdfPTable table_client = new PdfPTable(5);
            table_client.addCell("Id");
            table_client.addCell("Nombre");
            table_client.addCell("Email");
            table_client.addCell("Telefono");
            table_client.addCell("Dirección");

            try {
                Connection cn = Conexion.conect();
                PreparedStatement pst = cn.prepareStatement("select * from clientes");
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    do {
                        table_client.addCell(rs.getString(1));
                        table_client.addCell(rs.getString(2));
                        table_client.addCell(rs.getString(3));
                        table_client.addCell(rs.getString(4));
                        table_client.addCell(rs.getString(5));

                    } while (rs.next());
                    document.add(table_client);
                }

            } catch (SQLException e) {
                System.err.println("ERROR al generar lista de clientes. " + e);
            }
            document.close();
            JOptionPane.showMessageDialog(null, "Lista de clientes creada correctamente.");

        } catch (DocumentException | IOException e) {
            System.err.println("ERROR al generar PDF. " + e);
        }
    }//GEN-LAST:event_btn_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Capturista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_manageClients;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_registerCustomer;
    private javax.swing.JLabel label_Footer;
    private javax.swing.JLabel label_manageClients;
    private javax.swing.JLabel label_print;
    private javax.swing.JLabel label_registerCustomer;
    private javax.swing.JLabel label_userName;
    private javax.swing.JLabel label_wallpaper;
    // End of variables declaration//GEN-END:variables
}
