/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.nio.channels.GatheringByteChannel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author ma
 */
public class Tecnico extends javax.swing.JFrame {

    String user, name_user;
    int session_user;

    /**
     * Creates new form Tecnico.
     */
    public Tecnico() {
        initComponents();
        user = Login.user;
        session_user = Administrador.session_user;

        setSize(550, 300);
        setResizable(false);
        setTitle("Tecnico - Sesión de " + user);
        setLocationRelativeTo(null);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icon);
        this.repaint();

        if (session_user == 1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }

        try {
            Connection cn = Conexion.conect();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre_usuario from usuarios where username = '" + user + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                name_user = rs.getString("nombre_usuario");
                label_userName.setText("Bienvenido " + name_user);
            }

        } catch (SQLException e) {
            System.out.println("ERROR en consultar nombre del Tecnico.");
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_userName = new javax.swing.JLabel();
        btn_gestions = new javax.swing.JButton();
        label_registerCustomer = new javax.swing.JLabel();
        btn_graphicsStatus = new javax.swing.JButton();
        label_manageClients = new javax.swing.JLabel();
        btn_graphicsMake = new javax.swing.JButton();
        label_print = new javax.swing.JLabel();
        label_Footer = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_userName.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        label_userName.setForeground(new java.awt.Color(255, 255, 255));
        label_userName.setText("User");
        getContentPane().add(label_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn_gestions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apoyo-tecnico.png"))); // NOI18N
        btn_gestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestionsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gestions, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 100));

        label_registerCustomer.setForeground(new java.awt.Color(255, 255, 255));
        label_registerCustomer.setText("Gestion de Equipo");
        getContentPane().add(label_registerCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        btn_graphicsStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafica.png"))); // NOI18N
        btn_graphicsStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graphicsStatusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_graphicsStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 120, 100));

        label_manageClients.setForeground(new java.awt.Color(255, 255, 255));
        label_manageClients.setText("Grafica de Estatus");
        getContentPane().add(label_manageClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        btn_graphicsMake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafica.png"))); // NOI18N
        btn_graphicsMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graphicsMakeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_graphicsMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 120, 100));

        label_print.setForeground(new java.awt.Color(255, 255, 255));
        label_print.setText("Grafica de Marcas");
        getContentPane().add(label_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        label_Footer.setText("Creado por MrlnTrrzs13");
        getContentPane().add(label_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestionsActionPerformed
        GestionarEquipos manage_teams = new GestionarEquipos();
        manage_teams.setVisible(true);
    }//GEN-LAST:event_btn_gestionsActionPerformed

    private void btn_graphicsStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graphicsStatusActionPerformed
        GraficarEstatus graphicsStatus = new GraficarEstatus();
        graphicsStatus.setVisible(true);
    }//GEN-LAST:event_btn_graphicsStatusActionPerformed

    private void btn_graphicsMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graphicsMakeActionPerformed
         GraficarMarcas graphicsMake = new GraficarMarcas();
        graphicsMake.setVisible(true);
    }//GEN-LAST:event_btn_graphicsMakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gestions;
    private javax.swing.JButton btn_graphicsMake;
    private javax.swing.JButton btn_graphicsStatus;
    private javax.swing.JLabel label_Footer;
    private javax.swing.JLabel label_manageClients;
    private javax.swing.JLabel label_print;
    private javax.swing.JLabel label_registerCustomer;
    private javax.swing.JLabel label_userName;
    private javax.swing.JLabel label_wallpaper;
    // End of variables declaration//GEN-END:variables
}
